local M = {}

local function hl(group, spec)
  vim.api.nvim_set_hl(0, group, spec)
end

function M.apply(p)
  for index, color in ipairs(p.terminal) do
    vim.g["terminal_color_" .. (index - 1)] = color
  end

  hl("Normal", { fg = p.fg, bg = p.bg })
  hl("NormalNC", { fg = p.fg, bg = p.bg })
  hl("NormalFloat", { fg = p.fg, bg = p.bg_float })
  hl("FloatBorder", { fg = p.border, bg = p.bg_float })
  hl("FloatTitle", { fg = p.accent_text, bg = p.bg_float, bold = true })
  hl("Comment", { fg = p.comment, italic = true })
  hl("Constant", { fg = p.number })
  hl("String", { fg = p.string })
  hl("Character", { fg = p.string })
  hl("Number", { fg = p.number })
  hl("Boolean", { fg = p.number })
  hl("Float", { fg = p.number })
  hl("Identifier", { fg = p.variable })
  hl("Function", { fg = p.func })
  hl("Statement", { fg = p.keyword })
  hl("Conditional", { fg = p.keyword })
  hl("Repeat", { fg = p.keyword })
  hl("Label", { fg = p.keyword })
  hl("Operator", { fg = p.operator })
  hl("Keyword", { fg = p.keyword })
  hl("Exception", { fg = p.error })
  hl("PreProc", { fg = p.accent_text })
  hl("Include", { fg = p.keyword })
  hl("Define", { fg = p.keyword })
  hl("Macro", { fg = p.accent })
  hl("Type", { fg = p.type })
  hl("StorageClass", { fg = p.keyword })
  hl("Structure", { fg = p.type })
  hl("Typedef", { fg = p.type })
  hl("Special", { fg = p.accent })
  hl("SpecialChar", { fg = p.number })
  hl("Tag", { fg = p.tag })
  hl("Delimiter", { fg = p.punctuation })
  hl("SpecialComment", { fg = p.comment, italic = true })
  hl("Underlined", { fg = p.teal, underline = true })
  hl("Bold", { bold = true })
  hl("Italic", { italic = true })
  hl("Todo", { fg = p.accent_text, bold = true })
  hl("Error", { fg = p.error })
  hl("Added", { fg = p.success })
  hl("Changed", { fg = p.warning })
  hl("Removed", { fg = p.error })

  hl("Cursor", { fg = p.on_accent, bg = p.accent })
  hl("lCursor", { fg = p.on_accent, bg = p.accent })
  hl("CursorLine", { bg = p.line })
  hl("CursorColumn", { bg = p.line })
  hl("CursorLineNr", { fg = p.fg, bold = true })
  hl("LineNr", { fg = p.fg_soft })
  hl("SignColumn", { fg = p.fg_soft, bg = p.bg })
  hl("Folded", { fg = p.fg_muted, bg = p.bg_soft })
  hl("FoldColumn", { fg = p.fg_soft, bg = p.bg })
  hl("ColorColumn", { bg = p.bg_soft })
  hl("Conceal", { fg = p.fg_soft })
  hl("NonText", { fg = p.border })
  hl("EndOfBuffer", { fg = p.bg })
  hl("Whitespace", { fg = p.border })
  hl("SpecialKey", { fg = p.fg_soft })
  hl("MatchParen", { fg = p.accent, bold = true })
  hl("Visual", { bg = p.selection })
  hl("VisualNOS", { bg = p.selection })
  hl("Search", { bg = p.diff_mod })
  hl("IncSearch", { fg = p.on_accent, bg = p.accent })
  hl("CurSearch", { fg = p.on_accent, bg = p.accent })
  hl("Substitute", { fg = p.on_accent, bg = p.accent })
  hl("Pmenu", { fg = p.fg, bg = p.bg_float })
  hl("PmenuSel", { fg = p.fg_strong, bg = p.selection })
  hl("PmenuSbar", { bg = p.bg_soft })
  hl("PmenuThumb", { bg = p.fg_soft })
  hl("PmenuKind", { fg = p.accent_text, bg = p.bg_float })
  hl("StatusLine", { fg = p.fg, bg = p.bg_soft })
  hl("StatusLineNC", { fg = p.fg_muted, bg = p.bg_dim })
  hl("WinSeparator", { fg = p.border })
  hl("VertSplit", { fg = p.border })
  hl("TabLine", { fg = p.fg_muted, bg = p.bg_soft })
  hl("TabLineFill", { bg = p.bg_dim })
  hl("TabLineSel", { fg = p.fg_strong, bg = p.bg, bold = true })
  hl("Title", { fg = p.accent_text, bold = true })
  hl("WinBar", { fg = p.fg, bg = p.bg })
  hl("WinBarNC", { fg = p.fg_muted, bg = p.bg })
  hl("Directory", { fg = p.blue })
  hl("Question", { fg = p.teal })
  hl("MoreMsg", { fg = p.success })
  hl("ModeMsg", { fg = p.fg, bold = true })
  hl("ErrorMsg", { fg = p.error })
  hl("WarningMsg", { fg = p.warning })
  hl("WildMenu", { fg = p.fg_strong, bg = p.selection })
  hl("QuickFixLine", { bg = p.line })
  hl("DiffAdd", { bg = p.diff_add })
  hl("DiffChange", { bg = p.diff_mod })
  hl("DiffDelete", { bg = p.diff_del })
  hl("DiffText", { fg = p.warning, bg = p.diff_mod, bold = true })
  hl("SpellBad", { sp = p.error, undercurl = true })
  hl("SpellCap", { sp = p.blue, undercurl = true })
  hl("SpellLocal", { sp = p.teal, undercurl = true })
  hl("SpellRare", { sp = p.keyword, undercurl = true })

  hl("DiagnosticError", { fg = p.error })
  hl("DiagnosticWarn", { fg = p.warning })
  hl("DiagnosticInfo", { fg = p.teal })
  hl("DiagnosticHint", { fg = p.blue })
  hl("DiagnosticOk", { fg = p.success })
  hl("DiagnosticUnderlineError", { sp = p.error, undercurl = true })
  hl("DiagnosticUnderlineWarn", { sp = p.warning, undercurl = true })
  hl("DiagnosticUnderlineInfo", { sp = p.teal, undercurl = true })
  hl("DiagnosticUnderlineHint", { sp = p.blue, undercurl = true })
  hl("DiagnosticVirtualTextError", { fg = p.error, bg = p.diff_del })
  hl("DiagnosticVirtualTextWarn", { fg = p.warning, bg = p.diff_mod })
  hl("DiagnosticVirtualTextInfo", { fg = p.teal, bg = p.bg_soft })
  hl("DiagnosticVirtualTextHint", { fg = p.blue, bg = p.bg_soft })

  hl("@comment", { link = "Comment" })
  hl("@comment.documentation", { fg = p.comment, italic = true })
  hl("@constant", { fg = p.number })
  hl("@constant.builtin", { fg = p.number })
  hl("@string", { fg = p.string })
  hl("@string.escape", { fg = p.number, bold = true })
  hl("@string.regexp", { fg = p.teal })
  hl("@character", { fg = p.string })
  hl("@number", { fg = p.number })
  hl("@boolean", { fg = p.number })
  hl("@function", { fg = p.func })
  hl("@function.builtin", { fg = p.func })
  hl("@function.method", { fg = p.func })
  hl("@constructor", { fg = p.type })
  hl("@variable", { fg = p.variable })
  hl("@variable.builtin", { fg = p.keyword })
  hl("@variable.parameter", { fg = p.variable })
  hl("@variable.member", { fg = p.variable })
  hl("@property", { fg = p.variable })
  hl("@field", { fg = p.variable })
  hl("@type", { fg = p.type })
  hl("@type.builtin", { fg = p.type })
  hl("@keyword", { fg = p.keyword })
  hl("@keyword.function", { fg = p.keyword })
  hl("@keyword.operator", { fg = p.operator })
  hl("@keyword.import", { fg = p.keyword })
  hl("@keyword.return", { fg = p.keyword })
  hl("@operator", { fg = p.operator })
  hl("@punctuation", { fg = p.punctuation })
  hl("@punctuation.bracket", { fg = p.punctuation })
  hl("@punctuation.delimiter", { fg = p.punctuation })
  hl("@tag", { fg = p.tag })
  hl("@tag.attribute", { fg = p.attribute })
  hl("@tag.delimiter", { fg = p.punctuation })
  hl("@attribute", { fg = p.attribute })
  hl("@module", { fg = p.type })
  hl("@namespace", { fg = p.type })
  hl("@markup.heading", { fg = p.accent_text, bold = true })
  hl("@markup.heading.1", { fg = p.accent_text, bold = true })
  hl("@markup.heading.2", { fg = p.accent, bold = true })
  hl("@markup.strong", { fg = p.fg_strong, bold = true })
  hl("@markup.italic", { fg = p.fg, italic = true })
  hl("@markup.strikethrough", { fg = p.fg_muted, strikethrough = true })
  hl("@markup.underline", { underline = true })
  hl("@markup.link", { fg = p.teal, underline = true })
  hl("@markup.link.label", { fg = p.accent })
  hl("@markup.raw", { fg = p.string })
  hl("@markup.quote", { fg = p.string, italic = true })
  hl("@markup.list", { fg = p.accent })
  hl("@diff.plus", { fg = p.success })
  hl("@diff.minus", { fg = p.error })
  hl("@diff.delta", { fg = p.warning })

  hl("@lsp.type.namespace", { fg = p.type })
  hl("@lsp.type.type", { fg = p.type })
  hl("@lsp.type.class", { fg = p.type })
  hl("@lsp.type.enum", { fg = p.type })
  hl("@lsp.type.interface", { fg = p.type })
  hl("@lsp.type.struct", { fg = p.type })
  hl("@lsp.type.parameter", { fg = p.variable })
  hl("@lsp.type.variable", { fg = p.variable })
  hl("@lsp.type.property", { fg = p.variable })
  hl("@lsp.type.function", { fg = p.func })
  hl("@lsp.type.method", { fg = p.func })
  hl("@lsp.type.keyword", { fg = p.keyword })
  hl("@lsp.type.comment", { fg = p.comment, italic = true })
  hl("@lsp.type.string", { fg = p.string })
  hl("@lsp.type.number", { fg = p.number })
  hl("@lsp.type.operator", { fg = p.operator })
  hl("@lsp.type.decorator", { fg = p.accent })
  hl("LspReferenceText", { bg = p.bg_soft })
  hl("LspReferenceRead", { bg = p.bg_soft })
  hl("LspReferenceWrite", { bg = p.selection })
  hl("LspInlayHint", { fg = p.fg_muted, bg = p.bg_soft })
  hl("LspSignatureActiveParameter", { fg = p.accent_text, bold = true })

  hl("GitSignsAdd", { fg = p.success })
  hl("GitSignsChange", { fg = p.warning })
  hl("GitSignsDelete", { fg = p.error })
  hl("GitSignsAddLn", { bg = p.diff_add })
  hl("GitSignsChangeLn", { bg = p.diff_mod })
  hl("GitSignsDeleteLn", { bg = p.diff_del })
  hl("GitSignsCurrentLineBlame", { fg = p.fg_soft, italic = true })
  hl("NeogitDiffAdd", { bg = p.diff_add, fg = p.success })
  hl("NeogitDiffDelete", { bg = p.diff_del, fg = p.error })

  hl("TelescopeNormal", { fg = p.fg, bg = p.bg_float })
  hl("TelescopeBorder", { fg = p.border, bg = p.bg_float })
  hl("TelescopeTitle", { fg = p.accent_text, bold = true })
  hl("TelescopeSelection", { bg = p.selection })
  hl("TelescopeMatching", { fg = p.accent, bold = true })
  hl("TelescopePromptPrefix", { fg = p.accent })

  hl("SnacksPicker", { fg = p.fg, bg = p.bg_float })
  hl("SnacksPickerBorder", { fg = p.border, bg = p.bg_float })
  hl("SnacksPickerTitle", { fg = p.accent_text, bold = true })
  hl("SnacksPickerMatch", { fg = p.accent, bold = true })
  hl("SnacksPickerDir", { fg = p.blue })
  hl("SnacksIndent", { fg = p.border_soft })
  hl("SnacksIndentScope", { fg = p.accent })

  hl("NeoTreeNormal", { fg = p.fg, bg = p.bg_dim })
  hl("NeoTreeNormalNC", { fg = p.fg, bg = p.bg_dim })
  hl("NeoTreeDirectoryName", { fg = p.blue })
  hl("NeoTreeDirectoryIcon", { fg = p.accent })
  hl("NeoTreeRootName", { fg = p.accent_text, bold = true })
  hl("NeoTreeGitAdded", { fg = p.success })
  hl("NeoTreeGitDeleted", { fg = p.error })
  hl("NeoTreeGitModified", { fg = p.warning })
  hl("NeoTreeGitUntracked", { fg = p.teal })
  hl("NeoTreeIndentMarker", { fg = p.border })

  hl("BlinkCmpMenu", { fg = p.fg, bg = p.bg_float })
  hl("BlinkCmpMenuBorder", { fg = p.border, bg = p.bg_float })
  hl("BlinkCmpMenuSelection", { bg = p.selection })
  hl("BlinkCmpLabelMatch", { fg = p.accent, bold = true })
  hl("BlinkCmpKind", { fg = p.accent_text })
  hl("BlinkCmpDoc", { fg = p.fg, bg = p.bg_float })
  hl("BlinkCmpDocBorder", { fg = p.border, bg = p.bg_float })
  hl("BlinkCmpSignatureHelp", { fg = p.fg, bg = p.bg_float })
  hl("BlinkCmpGhostText", { fg = p.fg_soft })

  hl("NoiceCmdlinePopup", { fg = p.fg, bg = p.bg_float })
  hl("NoiceCmdlinePopupBorder", { fg = p.border, bg = p.bg_float })
  hl("NoiceCmdlineIcon", { fg = p.accent })
  hl("NotifyBackground", { bg = p.bg_float })
  hl("NotifyINFOBorder", { fg = p.teal })
  hl("NotifyWARNBorder", { fg = p.warning })
  hl("NotifyERRORBorder", { fg = p.error })
  hl("WhichKey", { fg = p.accent })
  hl("WhichKeyGroup", { fg = p.teal })
  hl("WhichKeyDesc", { fg = p.fg })
  hl("WhichKeySeparator", { fg = p.fg_soft })
  hl("FlashLabel", { fg = p.on_accent, bg = p.accent, bold = true })
  hl("FlashMatch", { fg = p.accent_text })
  hl("FlashCurrent", { fg = p.on_accent, bg = p.accent_active })
  hl("AerialLine", { bg = p.line })
  hl("AerialGuide", { fg = p.border })
  hl("MiniIndentscopeSymbol", { fg = p.accent })
  hl("LazyNormal", { fg = p.fg, bg = p.bg_float })
  hl("LazyButton", { fg = p.fg, bg = p.bg_soft })
  hl("LazyH1", { fg = p.on_accent, bg = p.accent, bold = true })
  hl("MasonHeader", { fg = p.on_accent, bg = p.accent })
  hl("DapBreakpoint", { fg = p.error })
  hl("DapStopped", { fg = p.success })
  hl("DapUIPlayPause", { fg = p.success })
  hl("DapUIStop", { fg = p.error })
end

return M
